#pragma once
#include "Cube/cube.h"
#include "brute_force.h"
#include "close_solution.h"
#include "corners.h"
#include "neighbours.h"
#include "one_phase.h"
#include "transposition_table.h"
#include "two_phase.h"
